### ISSUE TITLE
Unable to install RNSQLITE2

### ISSUE THREAD

**Issue by phinoppix** [craftzdog/react-native-sqlite-2#34]
I'm simply trying to yarn add the component to use with pouchdb adapter, but cannot get pass the build issue below.
```
gypgyp  info it worked if it ends withinfo ok
 it worked if it ends with ok
gyp info using node-gyp@3.6.2
gypgyp  info infousing node@10.4.1 | darwin | x64
 using node-gyp@3.6.2
gyp info using node@10.4.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
rm: ./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw: No such file or directory
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.4.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp  LIBTOOL-STATIC Release/sqlite3.a
 ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/Cellar/node/10.4.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd /Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/lib/binding/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.4.1/bin/node" "/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/phinoppix/workspace/pru/awb/workbench/node_modules/sqlite3/lib/binding/node-v64-darwin-x64' (1)
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
```
Versions used:
node = 10.4.1
react-native: 0.55.4
node_modules/nan = 2.10.0
node_modules/sqlite3 = 3.1.13

**Comment by craftzdog** [comment]
Why does it run gyp?
You don't need `sqlite3` dependency.
Follow the instruction properly.

**Comment by craftzdog** [comment]
Related to #38

**Comment by craftzdog** [comment]
Can you try v1.6.1?

**Comment by craftzdog** [comment]
No response. Closing.
